# portabeast kitty — exact Graphene palette from NixOS hyprland.nix
confirm_os_window_close 0

background #000000
foreground #dffcff
selection_background #333399
selection_foreground #ffffff
cursor #66cccc
cursor_text_color #000000
url_color #66cccc
active_border_color #66cccc
inactive_border_color #424153
active_tab_background #0066cc
active_tab_foreground #ffffff
inactive_tab_background #11142a
inactive_tab_foreground #a9cbd2

color0  #000000
color1  #ef708f
color2  #66cccc
color3  #e6b96c
color4  #0066cc
color5  #8b8be6
color6  #66cccc
color7  #dffcff
color8  #424153
color9  #ff8eaa
color10 #8ee6e6
color11 #f4cf8d
color12 #4b91ff
color13 #adadff
color14 #9af2f2
color15 #ffffff

map alt+shift+c copy_to_clipboard
map alt+shift+v paste_from_clipboard
